#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';

const cwd = process.cwd();
const cmd = process.argv[2] || 'help';

function exists(relPath) {
  return fs.existsSync(path.join(cwd, relPath));
}

function readJson(relPath) {
  try {
    return JSON.parse(fs.readFileSync(path.join(cwd, relPath), 'utf8'));
  } catch {
    return null;
  }
}

function findDocRoot() {
  const entries = fs.readdirSync(cwd, { withFileTypes: true });
  const doc = entries.find((entry) => entry.isDirectory() && entry.name.startsWith('[DOC]-'));
  return doc ? doc.name : null;
}

function walk(dir, max = 250, acc = []) {
  const full = path.join(cwd, dir);
  if (!fs.existsSync(full)) return acc;
  for (const entry of fs.readdirSync(full, { withFileTypes: true })) {
    if (acc.length >= max) return acc;
    if (['node_modules', '.next', 'dist', 'build', '.git'].includes(entry.name)) continue;
    const rel = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(rel, max, acc);
    else acc.push(rel);
  }
  return acc;
}

function ensureDir(relPath) {
  fs.mkdirSync(path.join(cwd, relPath), { recursive: true });
}

function write(relPath, content) {
  ensureDir(path.dirname(relPath));
  fs.writeFileSync(path.join(cwd, relPath), content, 'utf8');
}

function detectFramework(pkg) {
  const deps = { ...(pkg?.dependencies || {}), ...(pkg?.devDependencies || {}) };
  const found = [];
  for (const name of ['next', 'react', 'vue', 'svelte', '@angular/core', 'vite', 'tailwindcss', '@storybook/react', '@storybook/nextjs']) {
    if (deps[name]) found.push(`${name}@${deps[name]}`);
  }
  return found;
}

function scan() {
  const docRoot = findDocRoot();
  if (!docRoot) {
    console.error('No [DOC]-* directory found. Initialize project documentation before writing UX docs.');
    process.exitCode = 2;
    return;
  }

  const reportPath = path.join(docRoot, '11-UX-DesignOps', '08-Audits', 'Project_Scan_Report.md');
  const pkg = readJson('package.json');
  const files = walk('.', 250);
  const components = files.filter((f) => /component|components|ui/i.test(f) && /\.(tsx|jsx|vue|svelte)$/.test(f)).slice(0, 80);
  const routes = files.filter((f) => /(app|pages|routes)/i.test(f) && /\.(tsx|jsx|vue|svelte)$/.test(f)).slice(0, 80);
  const styles = files.filter((f) => /\.(css|scss|sass|less|pcss)$/.test(f)).slice(0, 80);
  const storybook = files.some((f) => /\.stories\.(tsx|jsx|ts|js|mdx)$/.test(f)) || exists('.storybook');
  const today = new Date().toISOString().slice(0, 10);

  const report = `---
title: UX Project Scan Report
type: ux-audit
status: draft
created: ${today}
updated: ${today}
tags:
  - ux
  - audit
  - project-scan
---

# UX Project Scan Report

Generated by \`scripts/ux/uxkit-lite.mjs scan\`.

## Package

- package.json: ${pkg ? 'found' : 'not found'}
- detected tools: ${detectFramework(pkg).join(', ') || 'none detected'}
- Storybook: ${storybook ? 'detected' : 'not detected'}
- DESIGN.md: ${exists('DESIGN.md') ? 'found' : 'not found'}
- AGENTS.md: ${exists('AGENTS.md') ? 'found' : 'not found'}

## Candidate routes/pages

${routes.map((f) => `- \`${f}\``).join('\n') || '- none detected'}

## Candidate UI components

${components.map((f) => `- \`${f}\``).join('\n') || '- none detected'}

## Style files

${styles.map((f) => `- \`${f}\``).join('\n') || '- none detected'}

## Next UX actions

1. Run \`$ux-audit\` on the most important route.
2. Create or update the related screen doc in \`11-UX-DesignOps/04-Screens\`.
3. Run \`$ux-component-spec\` on shared UI primitives.
4. Use \`$ux-mockup-generate\` for visual exploration if needed.
5. Use \`$ux-visual-verification\` after implementation.
`;

  write(reportPath, report);
  console.log(`Wrote ${reportPath}`);
}

if (cmd === 'scan') scan();
else {
  console.log(`uxkit-lite

Commands:
  node scripts/ux/uxkit-lite.mjs scan
`);
}
